# Generated by Django 4.1.4 on 2022-12-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('ReStock_Level', models.IntegerField(blank=True, null=True)),
                ('Qr_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Qr_image', models.ImageField(blank=True, null=True, upload_to='files/Qr_Codes')),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
