# Generated by Django 4.1.4 on 2022-12-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_inventorymodel_medication_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Medication_ID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseket', to='client.inventorymodel')),
            ],
        ),
    ]
