# Generated by Django 4.1.4 on 2022-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_completeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='dateField',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
