# Generated by Django 4.1.4 on 2022-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_inventorymodel_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymodel',
            name='shelf',
            field=models.CharField(blank=True, default='Yes', max_length=200, null=True),
        ),
    ]
