# Generated by Django 4.1.4 on 2023-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_medicationlabel_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_logo', models.ImageField(blank=True, null=True, upload_to='files/clinicLogo')),
            ],
        ),
    ]
